config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'posts#index'

  devise_for :users
  resources :posts do
    resource :reactions, only: %i[create destroy]
    resources :comments do
      resource :reactions, only: %i[create destroy]
      resources :comments
      resource :reports, only: %i[create destroy]
    end
    resources :suggestions, only: %i[new create show destroy accept] do
      resources :comments, only: %i[create edit update destroy]
    end
    resource :reports
  end
  get '/posts/accept/:id', to: 'posts#accept_post', as: 'moderator_accept'
  get '/profile/pending_posts', to: 'posts#profile', as: 'moderator_profile'
  get '/suggestions/accept', to: 'suggestions#accept', as: 'suggestion_accept'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :content, :user_id, :commentable_id, :commentable_type, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :reactions, as: :likeable, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  resourcify
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!, :find_comment_parent
  before_action :set_comment, only: %i[edit update]

  def create
    @comment = @comment_parent.comments.build(comment_params)
    authorize @comment
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post), notice: t(:comment_creation_success)
    else
      redirect_to post_path(@post), alert: t(:comment_creation_error)
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to @post, notice: t(:comment_updation_success)
    else
      render 'edit', alert: t(:comment_updation_error)
    end
  end

  def destroy
    @comment = @comment_parent.comments.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to post_path(@post), notice: t(:comment_delete_success) }
        format.js
      end
    else
      redirect_to post_path(@post), alert: t(:comment_delete_error)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end

  def find_comment_parent
    @post = Post.find(params[:post_id]) if params[:post_id]
    @comment_parent = Post.find(params[:post_id]) if params[:post_id]
    @comment_parent = Suggestion.find(params[:suggestion_id]) if params[:suggestion_id]
    @comment_parent = Comment.find(params[:comment_id]) if params[:comment_id]
  end
end

app/views/comments/_comment.html.erb
<% @post = get_post(post) %>

<% @post.comments.includes(:user).map do |comment| %>
  <div class="commentCon<%= comment.id %>">
    <p><%= comment.user.first_name %> Commented</p>
    <p><%= comment.content.html_safe %></p>
    <%= time_ago_in_words(comment.created_at) %> ago <br>
    <% if comment.comments.exists? %>
      <% comment.comments.map do |reply| %>
        <p><%= "#{User.find(reply.user_id).first_name} replied: #{reply.content.html_safe}" %></p>
      <% end %>
    <% end %>

    <div class="stats">
      <% if user_signed_in? %>
        <p id="commentsLikes"><%= comment.reactions.count %> Likes</p>
        <% if comment.reactions.find_by(user_id: current_user.id) %>
          <%= link_to 'unlike', post_comment_reactions_path(@post,comment), method: :delete, class: "btn btn-danger unlikecom" %>
        <% else %>
          <%= link_to 'like', post_comment_reactions_path(@post,comment), method: :post, class: "btn btn-success likecom" %>
        <% end %>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter<%= comment.id %>">
          Reply
        </button>
        <% if comment.user_id == current_user.id %>
          <%= link_to 'Edit', edit_post_comment_path(@post,comment), class: "btn btn-primary" %>
        <% end %>
        <% if user_signed_in? %>
          <% if comment_owner?(comment) || post_owner?(post) || role?(:admin) %>
            <%= link_to 'Delete Comment', post_comment_path(@post,comment), method: :delete, data: {confirm: 'Are You Sure You Want To Delete This Comment?'}, remote: true, class: "btn btn-danger delcom" %>
          <% end %>
        <% end %>
      <% else %>
        <i class="fa fa-thumbs-up icon"></i><%= comment.reactions.count %>
      <% end %>
      <br><br>
      <!--MODAL REPLY-->
      <div class="modal fade" id="exampleModalCenter<%= comment.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Reply</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            <h2>Add a Reply</h2>
              <%= form_for([@post, comment, Comment.new]) do |f| %>
                <%= f.text_area :content, class: 'form-control' %>
                <%= f.hidden_field :user_id, :value => current_user.id %><br>
                <%= f.submit class: 'btn btn-primary', value: 'Add'%>
              <% end %>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <!--MODAL ENDS-->
    </div>
  </div>
<% end %>

app/views/comments/_commentup.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <%= f.cktext_area :content, class: 'form-control' %>
  <%= f.hidden_field :user_id, :value => current_user.id %><br>
  <%= f.submit class: 'btn btn-primary'%>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], :remote => true) do |f| %>
  <%= f.cktext_area :content, class: 'form-control' %>
  <%= f.submit class: 'btn btn-primary addcombtn' %>
<% end %>

app/views/comments/destroy.js.erb
$('.delcom').bind('ajax:success', function(){
  $('.commentCon<%= @comment.id %>').hide();
  $('#likesCount').text(<%= @post.reactions.count %>+" Likes "+<%= @post.comments.count %>+" Comments");
});

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= render 'comments/commentup' %>

app/views/comments/new.html.erb
<%= render 'form' %>