config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'posts#index'

  devise_for :users
  resources :posts do
    resource :reactions, only: %i[create destroy]
    resources :comments do
      resource :reactions, only: %i[create destroy]
      resources :comments
      resource :reports, only: %i[create destroy]
    end
    resources :suggestions, only: %i[new create show destroy accept] do
      resources :comments, only: %i[create edit update destroy]
    end
    resource :reports
  end
  get '/posts/accept/:id', to: 'posts#accept_post', as: 'moderator_accept'
  get '/profile/pending_posts', to: 'posts#profile', as: 'moderator_profile'
  get '/suggestions/accept', to: 'suggestions#accept', as: 'suggestion_accept'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  scope :with_approval, -> { where(approved: true) }
  scope :without_approval, -> { where('approved = false') }

  validates :title, :user_id, presence: true
  paginates_per 3
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :reactions, as: :likeable, dependent: :destroy
  has_many :suggestions, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy
  resourcify
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy accept_post]

  def index
    @posts = Post.includes(:user).with_approval.order(created_at: :desc).page(params[:page])
    respond_to do |format|
      format.json { render json: @posts }
      format.html
    end
  end

  def new
    @post = current_user.posts.build
    authorize @post
  end

  def create
    @post = current_user.posts.build(post_params)
    authorize @post
    @post.approved = false
    @post.approved = true if @post.user.has_role?(:moderator) || @post.user.has_role?(:admin)
    if @post.save
      if @post.approved
        redirect_to @post, notice: t(:post_created)
      else
        redirect_to root_path, notice: t(:post_submission)
      end
    else
      redirect_to new_post_path, alert: t(:post_submission_error)
    end
  end

  def show
    respond_to do |format|
      format.json { render json: @post }
      format.html
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: t(:post_update)
    else
      render 'edit', alert: t(:post_update_error)
    end
  end

  def destroy
    if @post.destroy
      respond_to do |format|
        format.js   { flash[:notice] = 'Post Deleted Successfully!' }
        format.html { redirect_to root_path, notice: t(:post_delete_success) }
      end
    else
      render @post, alert: t(:post_delete_error)
    end
  end

  def profile
    authorize current_user
    @posts = Post.includes(:user).without_approval.order(created_at: :desc).page(params[:page])
    @all_posts = Post.all
  end

  def accept_post
    authorize current_user
    @post.approved = true
    @post.save
    redirect_to root_path, notice: t(:post_approval_success)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :approved)
  end

  def set_post
    @post = Post.find(params[:id])
    authorize @post
  end
end

app/views/posts/_form.html.erb
<%= form_with model: @post do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>
  <%= f.label :content %><br>
  <%= f.cktext_area :content %><br><br>
  <%= f.submit %>
<% end %>

app/views/posts/destroy.js.erb
$('.deletebtn').bind('ajax:success', function(){
  $('.postContent<%= @post.id %>').hide();

});

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Hello to Blog Post Application!</h1>
  <p class="lead">We Provide The Fascility to Add, Remove, View and Delete Posts on This Application.</p>
  <hr class="my-4">
  <p>People Can View Posts on This Application and Interact with each other by commenting. Sign Up for Adding Yours Today!</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="<%= new_post_path %>" role="button">Add New post</a>
  </p>
</div>


<div class="container">
  <div class="row" id="postRow">
    <% @posts.map do |post| %>

      <div class="col-lg-4 col-md-4 col-sm-4 col-12">
        <div class="postContent<%= post.id %>">
          <a href="<%= post_path(post) %>" id="postContainer">
            <div class="jumbotron">
              <h3 class="postTitleIndex"><strong>Post Title</strong>: <%= post.title %></h3>
              <p><strong>Posted by</strong>: <%= post.user.first_name %></p>
              <p><strong>Likes</strong>: <%= post.reactions.count %></p>
              <% if post.comments.exists? %>
                <p id="postContentIndex"><strong>Latest Comment</strong>: <%= truncate(post.comments.last.content.html_safe, length: 2) %></p>
              <% else %>
                <p><strong>No Comments Yet</strong></p>
              <% end %>
              <p><%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>
            </div>
          </a>
          <p class="lead">
            <% if user_signed_in? %>
              <% if post_owner?(post) || role?(:admin) || role?(:moderator) %>
                <%= link_to 'Delete post', post_path(post), method: :delete, data: {confirm: 'Are You Sure You Want To Delete This Post?'},remote: true, :class => "btn btn-danger deletebtn" %>
              <% end %>
              <% if post_owner?(post) || role?(:admin) %>
                <%= link_to 'Edit post', edit_post_path(post), :class => "btn btn-primary" %>
              <% end %>
            <% end %>
            <%= link_to 'Show', post_path(post), :class => "btn btn-primary" %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>Create New Post</h1>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= render 'form' %>

app/views/posts/profile.html.erb
<div class="jumbotron">
  <h1 class="display-4">You May Approve or Unpublish/Delete a Post</h1>
</div>


<% @posts.map do |post| %>
  <% if !post.approved && !post.user.has_role?(:moderator) && !post.user.has_role?(:admin) %>
    <div class="col-lg-4 col-md-4 col-sm-4 col-12">
      <h3 class="postTitleIndex"><strong>Post Title</strong>: <%= post.title %></h3>
      <p><strong>Posted by</strong>: <%= post.user.first_name %></p>
      <p><strong>Likes</strong>: <%= post.reactions.count %></p>
      <% if post.comments.exists? %>
        <p><strong>Latest Comment</strong>: <%= post.comments.last.content %></p>
      <% else %>
        <p><strong>No Comments Yet</strong></p>
      <% end %>
      <p><%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>

      <p class="lead">
        <%= link_to 'Delete post', post_path(post), method: :delete, data: {confirm: 'Are You Sure You Want To Delete This Post?'}, :class => "btn btn-danger" %>
        <%= link_to 'Show', post_path(post), :class => "btn btn-primary" %>
        <%= link_to 'Approve', moderator_accept_path(post), :class => "btn btn-success" %>
      </p>
    </div>
  <% end%>
<% end %>



<% @all_posts.each do |post| %>
  <% if post.reports.exists? %>
    <div class="col-lg-4 col-md-4 col-sm-4 col-12">
      <h3 class="postTitleIndex"><strong>Post Title</strong>: <%= post.title %></h3>
      <p><strong>Posted by</strong>: <%= post.user.first_name %></p>
      <p><strong>This Post Has Been Reported <%= post.reports.count %> time(s)</strong></p>
      <p><strong>Kindly Take Necessary Actions for this Post</strong></p>
      <p><%= distance_of_time_in_words(post.created_at, Time.now) %> ago</p>

      <p class="lead">
        <%= link_to 'Delete post', post_path(post), method: :delete, data: {confirm: 'Are You Sure You Want To Delete This Post?'}, :class => "btn btn-danger" %>
        <%= link_to 'Show', post_path(post),  class: "btn btn-primary" %>
      </p>
    </div>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">Posted By <%= @post.user.first_name %></h1>
  <hr class="my-4">
<% if user_signed_in? %>
  <% if suggestion_owner?(@post) || post_owner?(@post) || role?(:admin) %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter2">
      View Suggestions
    </button>
  <% end %>
  <% if current_user != @post.user %>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
      Add Suggestion
    </button>
  <% end %>
<% end %>

  <!-- Post Content -->
  <div class="container">
    <h2><strong>Title</strong>: <%= @post.title %></h2>
    <h3><strong>Description</strong>: <%= @post.content.html_safe %></h3>
    <p><%= distance_of_time_in_words(@post.created_at, Time.now) %> ago</p>

    <div class="stats">
      <% if user_signed_in? %>
        <p id="likesMsg"></p>
        <p id="likesCount"><%= @post.reactions.count %> Likes  <%= @post.comments.count %> Comments </p>
        <%= link_to 'unlike', post_reactions_path(@post), method: :delete, class: "btn btn-danger btn-lg unlikebtn", remote: true %>
        <%= link_to 'like', post_reactions_path(@post), method: :post, class: "btn btn-success btn-lg likebtn", remote: true %>
        <% if report_owner?(@post) %>
          <%= link_to 'Undo Report', post_reports_path(@post), method: :delete, class: "btn btn-primary btn-lg" %>
        <% else %>
          <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#reportModal<%= @post.id %>">
          Report
        </button>
        <% end %>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#commentModal<%= @post.id %>">
          Comment
        </button>
      <% else %>
        <p><%= @post.reactions.count %> Likes</p>
      <% end %>
    </div>
    <br>

  <!-- Delete and Edit Buttons -->
    <p class="lead">
      <% if user_signed_in? %>
        <% if post_owner?(@post) || role?(:admin) || role?(:moderator) %>
          <%= link_to 'Delete post', post_path(@post), method: :delete, data: {confirm: 'Are You Sure You Want To Delete This Post?'}, remote: true, :class => "btn btn-danger btn-lg deletebtn" %>
        <% end %>
        <% if post_owner?(@post) || role?(:admin) %>
          <%= link_to 'Edit post', edit_post_path(@post), :class => "btn btn-primary btn-lg" %>
        <% end %>
      <% end %>
      <%= link_to 'Back', root_path, :class => "btn btn-primary btn-lg" %>
    </p>
  </div>
</div>

<!--Modal Report-->
<div class="modal fade" id="reportModal<%= @post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Reports</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if user_signed_in? %>
          <h2>Reason For Reporting</h2>
          <%= render 'reports/form' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!--Modal Comment -->
<div class="addComModal modal fade" id="commentModal<%= @post.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if user_signed_in? %>
          <h2>Add Comment</h2>
          <%= render 'comments/form' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal Add Suggestion -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Suggestions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if user_signed_in? %>
          <h2>Add a Suggestion</h2>
          <p>Use Format <strong>Text to Change:Text to Insert</strong></p>
          <%= render 'suggestions/form' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!-- Modal Show Suggestions -->
<div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Suggestions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div>

      <% if user_signed_in? %>
        <% if @post.suggestions.count != 0 %>
          <%= render 'suggestions/suggestion', post: @post %>
        <% end %>
      <% end %>
       </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<!--Show Comments -->
  <h2 id="showCommentsHead">Comments <i class="fa fa-arrow-down" aria-hidden="true"></i></h2>

  <div id="showComments">
    <% if @post.comments.count != 0 %>
      <%= render 'comments/comment', post: @post %>
    <% end %>
  </div>
<!-- End Post Content -->
</div>
<!-- Jumbotron Ends -->

<script>
$('#showComments').hide();
$("#showCommentsHead").click(function(){

  $('#showComments').toggle();


});


</script>