config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'posts#index'

  devise_for :users
  resources :posts do
    resource :reactions, only: %i[create destroy]
    resources :comments do
      resource :reactions, only: %i[create destroy]
      resources :comments
      resource :reports, only: %i[create destroy]
    end
    resources :suggestions, only: %i[new create show destroy accept] do
      resources :comments, only: %i[create edit update destroy]
    end
    resource :reports
  end
  get '/posts/accept/:id', to: 'posts#accept_post', as: 'moderator_accept'
  get '/profile/pending_posts', to: 'posts#profile', as: 'moderator_profile'
  get '/suggestions/accept', to: 'suggestions#accept', as: 'suggestion_accept'
end

app/models/suggestion.rb
# frozen_string_literal: true

class Suggestion < ApplicationRecord
  validates :user_id, :post_id, :content, presence: true
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  belongs_to :post
  resourcify
end

app/controllers/suggestions_controller.rb
# frozen_string_literal: true

class SuggestionsController < ApplicationController
  before_action :find_post, only: %i[create destroy]

  def new; end

  def create
    @suggestion = @post.suggestions.build(suggestion_params)
    authorize @suggestion
    if @suggestion.save
      redirect_to post_path(@post), notice: t(:suggestion_success)
    else
      redirect_to post_path(@post), alert: t(:suggestion_error)
    end
  end

  def show; end

  def destroy
    @suggestion = Suggestion.find_by(post_id: @post.id)
    authorize @suggestion
    if @suggestion.destroy
      redirect_to post_path(@post), notice: t(:suggestion_rejection)
    else
      render @post, alert: t(suggestion_destroy_error)
    end
  end

  def accept
    @suggestion = Suggestion.find(params[:format])
    authorize @suggestion
    @post = @suggestion.post

    if @suggestion.content.include? ':'
      text_before = @suggestion.content.split(':')[0]
      text_after = @suggestion.content.split(':')[1]

      if @post.content.gsub(text_before, text_after)
        new_desc = @post.content.gsub(text_before, text_after)
        @post.content = new_desc
        @post.save
        msg = t(:suggestion_accept)
      else
        msg = t(:suggestion_msg)
      end
    else
      msg = t(:suggestion_not_implemented)
    end
    if @suggestion.destroy
      redirect_to @post, notice: msg
    else
      render @post, alert: t(:suggestion_error)
    end
  end

  private

  def suggestion_params
    params.require(:suggestion).permit(:user_id, :content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/views/suggestions/_form.html.erb
<%= form_for([@post, @post.suggestions.build]) do |f| %>
  <%= f.text_field :content, class: 'form-control' %>
  <%= f.hidden_field :user_id, :value => current_user.id %><br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/suggestions/_suggestion.html.erb
<% @post = get_post(post) %>

<% @post.suggestions.each do |suggestion| %>
  <% @user = get_suggestion_owner(suggestion) %>
  <div>
    <% if suggestion_given_by?(suggestion) || post_owner?(@post) %>
      <p><%= suggestion.content %></p>
      <p><%= 'by '+ @user.first_name %></p>
      <%= time_ago_in_words(suggestion.created_at) +' ago' if suggestion.created_at %><br>
      <% if post_owner?(@post) || role?(:admin) %>
        <%= link_to 'Accept', suggestion_accept_path(suggestion), :class => "btn btn-success" %>
        <%= link_to 'Reject Suggestion', post_suggestion_path(@post,suggestion), method: :delete, data: {confirm: 'Are You Sure You Want To Delete This Suggestion?'}, :class => "btn btn-danger" %>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter<%= suggestion.id %>">
          Reply
        </button><br>
      <% end %><br><br>
      <% suggestion.comments.each do |sugg_reply| %>
        <%= "#{get_suggestion_reply_user_name(sugg_reply)} replied: #{sugg_reply.content}" %><br>
      <% end %>


    <div class="modal fade" id="exampleModalCenter<%= suggestion.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Suggestions</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <% if post_owner?(@post) || role?(:admin)%>
            <div class="modal-body">
              <h2>Add a Reply</h2>
              <%= form_for([@post, suggestion, Comment.new]) do |f| %>
                <%= f.text_field :content, class: 'form-control' %>
                <%= f.hidden_field :user_id, :value => current_user.id %><br>
                <%= f.submit class: 'btn btn-primary', value: 'Add'%>
              <% end %>
            </div>
          <% end %>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>